[build-system]
requires = [ "setuptools", "wheel", "oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "macauff"
version = "0.1.0"
readme = "README.md"
# 3.12 has removed distutils
requires-python = ">=3.8,<3.12"
dependencies = [
    "astropy",
    "matplotlib",
    "numpy",
    "pandas",
    "skypy",
    "speclite",
]

[project.optional-dependencies]
test = [
    "pytest-astropy",
    "scipy",
]
docs = [
    "sphinx-astropy",
    "sphinx-fortran",
    "six",
]

[tool.cibuildwheel]
build-frontend = "build"
config-settings = { "build-args" = "--full-build" }
skip = [
    "pp*"  # we don't support PyPy
]
